export default questions = [
	{
		id: 1,
		char: 'pop',
		statement: 'Queremos mais fontes limpas de energia, a poluição está nos incomodando! Coloque mais painéis solares na nossa região!',
		yesOption: 'Tudo bem',
		noOption: 'Não',
		yes: [2, 2, -4, 2],
		no: [-2, -4, 2, -2],
	},
	{
		id: 2,
		char: 'rob',
		statement: 'Eu acho que deveríamos construir uma hidrelétrica no Rio Elma, que fica na planície de São Pedro, o que senhor acha?',
		yesOption: 'Construa',
		noOption: 'Não construa',
		yes: [-2, -2, -4, 1],
		no: [2, 2, 0, -1],
	},
	{
		id: 3,
		char: 'jon',
		statement: 'Recebemos uma proposta de doação de certo valor para a construção de um parque eólico no Mar Olimpo, o senhor deveria aceitar!',
		yesOption: 'Aceito',
		noOption: 'Não aceito',
		yes: [2, 2, 0, 4],
		no: [-1, -2, 0, -2],
	},
	{
		id: 4,
		char: 'car',
		statement: 'Poderíamos vender um pouco da nossa terra para investidores estrangeiros!',
		yesOption: 'Claro!',
		noOption: 'Nunca!',
		yes: [-4, -2, 4, 0],
		no: [4, 2, -2, 0],
	},
	{
		id: 5,
		char: 'rob',
		statement: 'Os outros países estão optando por usinas termoelétricas, o combustível é muito barato! Vamos colocar uma no nosso país!',
		yesOption: 'Tudo bem',
		noOption: 'Não',
		yes: [-4, -2, -2, 4],
		no: [2, 2, 0, -2],
	},
	{
		id: 6,
		char: 'jon',
		statement: 'Percebemos que a usina maremotriz de Santo Antônio está precisando de manutenção, o senhor poderia financiar o procedimento?',
		yesOption: 'Claro!',
		noOption: 'Se está funcionando, está ótimo...',
		yes: [2, 0, -2, 2],
		no: [-1, 0, 1, -2],
	},
	{
		id: 7,
		char: 'pop',
		statement: 'A usina nuclear de São Bento está nos incomodando! Não vamos mais aguentar tanta radiação, por favor, retire ela!',
		yesOption: 'Vou retirar',
		noOption: 'Ela é importante...',
		yes: [2, 2, -2, -4],
		no: [-1, -4, 2, 2],
	},
	{
		id: 8,
		char: 'rob',
		statement: 'Vejo um grande potencial de construção de uma hidrelétrica na bacia do Rio Tupi, seria uma importante fonte de energia, que poderíamos vender futuramente!',
		yesOption: 'Construa',
		noOption: 'Não construa',
		yes: [-4, -2, -2, 4],
		no: [4, 2, 2, -2],
	},
	{
		id: 9,
		char: 'car',
		statement: 'Alguns países querem comprar um pouco da nossa energia, acho que seria interessante para aumentar nossos ganhos!',
		yesOption: 'Venda!',
		noOption: 'O que produzimos é só nosso!',
		yes: [-1, 0, 4, -2],
		no: [1, 0, -2, 2],
	},
	{
		id: 10,
		char: 'jon',
		statement: 'O parque eólico do Mar Olimpo funciona com irregularidades. Devem ser feitas manutenções no local!',
		yesOption: 'Concordo',
		noOption: 'Não será necessário',
		yes: [2, 0, -2, 2],
		no: [-2, 0, 1, -2],
	},
	{
		id: 11,
		char: 'rob',
		statement: 'Já está na hora de começarmos a utilizar fontes mais baratas! Acho que o carvão mineral é uma boa ideia, concorda?',
		yesOption: 'Claro!',
		noOption: 'Não. Polui muito!',
		yes: [-4, -2, 4, 4],
		no: [4, 2, -2, -2],
	},
	{
		id: 12,
		char: 'pop',
		statement: 'Aqui no município de Bom Destino chega somente uma energia fraca, sugerimos a instalação de turbinas eólicas, o local é bom!',
		yesOption: 'Boa ideia!',
		noOption: 'Não será possível.',
		yes: [2, 2, -2, 2],
		no: [0, -2, 2, -2],
	},
	{
		id: 13,
		char: 'rob',
		statement: 'Devemos trocar os sistemas de iluminação de algumas cidades para lâmpadas LED, assim a longo prazo teremos menos custo em energia! O que o senhor acha?',
		yesOption: 'Você tem razão!',
		noOption: 'Dará muito trabalho...',
		yes: [2, 2, 2, 2],
		no: [-2, -2, -2, -2],
	},
	{
		id: 14,
		char: 'jon',
		statement: 'SENHOR!! A barragem da usina hidrelétrica de São Pedro se rompeu! Temos que reconstruí-la ou suspendê-la!',
		yesOption: 'Reconstrua já!',
		noOption: 'Suspenda agora!',
		yes: [-2, -2, -4, 4],
		no: [2, 2, 2, -4],
	},
	{
		id: 15,
		char: 'car',
		statement: 'A população está muito exigente! Para satisfazermos seus pedidos precisamos de muito dinheiro, devemos aumentar os impostos!',
		yesOption: 'Certamente!',
		noOption: 'Não será preciso.',
		yes: [0, -4, 4, 0],
		no: [0, 4, -2, 0],
	},
	{
		id: 16,
		char: 'rog',
		statement: 'Olá governador, sou dono da empresa Mais Energia e gostaria da sua autorização para a construção de uma usina termelétrica próximo à Vila da Paz.',
		yesOption: 'Está autorizado',
		noOption: 'Não autorizarei',
		yes: [-4, -2, 0, 2],
		no: [0, 1, 0, 0],
	},
	{
		id: 17,
		char: 'rog',
		statement: 'Governador, nossa usina está a todo vapor e gerando diversos empregos! Poderíamos expandí-la?',
		yesOption: 'Com certeza!',
		noOption: 'Não',
		yes: [-4, -1, 2, 4],
		no: [2, 1, -2, -2],
	},
	{
		id: 18,
		char: 'rog',
		statement: 'Governador, estamos interessados em uma parceria com a mais nova mina de carvão para suprir nossa termelétrica! O que acha?',
		yesOption: 'Parece um bom negócio',
		noOption: 'Não no momento',
		yes: [-4, -2, 2, 4],
		no: [0, 2, -1, -1],
	},
	{
		id: 19,
		char: 'igo',
		statement: 'Governador, de acordo com minhas pesquisas, há uma concentração enorme de poluentes no ar nas proximidades da Vila da Paz, devido à usina termelétrica. Precisamos que instalem filtros nas chaminés!',
		yesOption: 'Providenciarei isso',
		noOption: 'Não é problema meu',
		yes: [2, 1, -1, 0],
		no: [-2, -4, 2, 0],
	},
	{
		id: 20,
		char: 'igo',
		statement: 'URGENTE! A usina termelétrica é uma ameaça iminente à natureza da região da Vila da Paz! Precisamos de sua remoção imediata!',
		yesOption: 'Farei isso imediatamente!',
		noOption: 'Jamais!',
		yes: [2, 2, -4, -4],
		no: [-4, -4, 2, 1],
	},
	{
		id: 21,
		char: 'rog',
		statement: 'Pensei que tínhamos uma parceria! Removerei TODO o investimento que já havia feito na região!',
		yesOption: 'Vá embora!',
		noOption: 'Espere!',
		yes: [, 2, -4, -4],
		no: [, 2, -4, , 2, -4, -4],
	},
	{
		id: 22,
		char: 'igo',
		statement: 'Governador, poderia subsidiar meu projeto de pesquisa a respeito de formas mais eficazes e ecológicas de produção de energia?',
		yesOption: 'Com certeza!',
		noOption: 'Não estou interessado',
		yes: [0, 0, -2, 0],
		no: [0, 0, 0, 0],
	},
	{
		id: 23,
		char: 'igo',
		statement: 'Governador, infelizmente tive problemas com a pesquisa e a verba disponibilizada não está sendo suficiente. Poderia aumentar o auxílio?',
		yesOption: 'Ok…',
		noOption: 'Não tenho verba para isso',
		yes: [0, 0, -4, 0],
		no: [0, 0, 0, 0],
	},
	{
		id: 24,
		char: 'igo',
		statement: 'Governador, finalmente concluí minha pesquisa! Com um pequeno incentivo final, posso aplicar minhas invenções nas usinas geradoras de energia!',
		yesOption: 'Aqui está!',
		noOption: 'Não tenho mais interesse',
		yes: [4, 2, -2, 4],
		no: [0, 0, 0, 0],
	},
	{
		id: 25,
		char: 'jon',
		statement: 'SENHOR! A usina nuclear de São Bento emitiu muita radiação nos últimos dias, está muito perigoso e precisa de medidas! Agora o senhor precisa arcar com os custos!',
		yesOption: 'Com certeza!',
		noOption: 'Deixe como está…',
		yes: [4, 4, -4, -4],
		no: [-4, -4, 2, 4],
	},
	{
		id: 26,
		char: 'jon',
		statement: 'Devido ao rompimento da barragem da usina de São Pedro, cidades locais ficaram sem energia. O que acha de construímos um parque solar na região?',
		yesOption: 'Claro!',
		noOption: 'Não é a melhor opção...',
		yes: [2, 4, -2, 4],
		no: [0, -4, 2, -2],
	},
	{
		id: 27,
		char: 'pop',
		statement: 'A usina termelétrica da empresa Mais Energia está oferecendo condições insalubres de trabalho aos moradores da Vila da Paz! Precisamos da sua intervenção!',
		yesOption: 'Resolverei isso!',
		noOption: 'Não interferirei nas decisões da empresa',
		yes: [0, 4, -2, -4],
		no: [0, -4, 2, 0],
	},
];
