export default questions = [
	{
		id: 1,
		statement: 'Teste 1',
		yesOption: 'Sim',
		noOption: 'Não',
		yes: [1, -1, 1, -1],
		no: [-1, 2, -1, 3],
	},
	{
		id: 2,
		statement: 'Teste 2',
		yesOption: 'Sim',
		noOption: 'Não',
		yes: [2, 2, 2, 2],
		no: [-2, -2, -2, -2],
	},
	{
		id: 3,
		statement: 'Teste 3',
		yesOption: 'Sim',
		noOption: 'Não',
		yes: [1, 0, 1, 0],
		no: [0, -2, 0, 0],
	},
	{
		id: 4,
		statement: 'Teste 4',
		yesOption: 'Sim',
		noOption: 'Não',
		yes: [0, 0, 0, 1],
		no: [0, -1, 0, 0],
	},
	{
		id: 5,
		statement: 'Teste 5',
		yesOption: 'Sim',
		noOption: 'Não',
		yes: [1, 2, 3, 4],
		no: [-4, -3, -2, -1],
	},
	{
		id: 6,
		statement: 'Teste 6',
		yesOption: 'Sim',
		noOption: 'Não',
		yes: [1, 2, 3, 4],
		no: [-4, -3, -2, -1],
	},
	{
		id: 7,
		statement: 'Teste 7',
		yesOption: 'Exatamente',
		noOption: 'Com certeza',
		yes: [10, -10, 10, -10],
		no: [0, 1, 0, 0],
	},
];
